name: path-to-success-again
services:
  web:
    build: .
    ports:
      - "1337:1337"
    command: [ "hypercorn", "app:app", "--bind", "0.0.0.0:1337", "--debug", "--reload" ]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
volumes:
  db-data:
